### ISSUE TITLE
Support for X-Ray remote sampling.

### ISSUE THREAD

**Issue by RyanW8** [aws-observability/aws-otel-js#125]
Pretty self explanatory, is support for X-Ray remote sampling on the roadmap for anytime soon?

**Comment by willarmiros** [comment]
Hi @RyanW8 - thanks for raising this. It is certainly on the roadmap however we cannot provide dates over GitHub. We will keep this issue open to track support for it, and feel free to keep an eye on opentelemetry-js-contrib for relevant PRs 😉

**Comment by RyanW8** [comment]
We have AWS Enterprise support and are under NDA. If I open a case will I be able to get a rough ETA?

**Comment by willarmiros** [comment]
Yes :)
