### ISSUE TITLE
End to end Test failed due to incorrect trace format

### ISSUE THREAD

**Issue by wyTrivail** [aws-observability/aws-otel-js#19]
while checking the e2e test failure, i found the log in otcollector as below:

```
aws-ot-collector_1  | Span #0
aws-ot-collector_1  |     Trace ID       : e5ff1f6fc69c69a7dff5df74ebdf79dfaf3b7b87b8edee1f
aws-ot-collector_1  |     Parent ID      :
aws-ot-collector_1  |     ID             : 7b6efc69e75ff34f387dcd7b
aws-ot-collector_1  |     Name           : GET /
aws-ot-collector_1  |     Kind           : SPAN_KIND_SERVER
aws-ot-collector_1  |     Start time     : 2020-10-21 04:27:24.78015232 +0000 UTC
aws-ot-collector_1  |     End time       : 2020-10-21 04:27:26.786455808 +0000 UTC
aws-ot-collector_1  |     Status code    : STATUS_CODE_OK
aws-ot-collector_1  |     Status message :
```

the trace id is not a valid xray trace id. 

However, the sample app returned trace id as

```
➜  ~ curl http://127.0.0.1:4567/
{"traceId":"1-5f8fb8ac-aaff9d9069953687e4e47e4f"}%
```

I'm not sure which part is having issue at this moment, but looks like jssdk sends a wrong trace id?

**Comment by KKelvinLo** [comment]
There is a fix currently being implemented described in this [issue](https://github.com/open-telemetry/opentelemetry-js/issues/1623) of the upstream repo.

**Comment by wyTrivail** [comment]
looks like the code is merged, can we check if it can fix this issue?

**Comment by KKelvinLo** [comment]
There's a dependency issue waiting on the upstream release of this [PR#1627](https://github.com/open-telemetry/opentelemetry-js/pull/1627) before the traces are exported correctly.

**Comment by awssandra** [comment]
What's the status here? The PR referenced looks like it's merged.

**Comment by KKelvinLo** [comment]
@awssandra I've symlinked the dependencies locally for exporter-collector-grpc and everything passes. However, ourtests are blocked and cannot call the new dependency until [upstream](https://github.com/open-telemetry/opentelemetry-js) has a release.
