### ISSUE TITLE
AWS Resources not recognised (AWS SDK v3 support)

### ISSUE THREAD

**Issue by noliva** [aws-observability/aws-otel-js#45]
Hello,

I have the following example that makes use of the `aws-collector` and the open-telemetry instrumentation.

This is the repo and the exact commit: https://github.com/noliva/aws-observability/tree/f9e5abba1c1e240f90e56d1fc0f390c6f453874e

Basically, the problem is that when I do any requests to that service I don't see the DynamoDB instrumentation or the response code in the X-Ray console.

This is what a request looks like in the console:

<img width="1479" alt="Screenshot 2020-12-18 at 16 38 52" src="https://user-images.githubusercontent.com/2056101/102638569-9f8d6e00-414f-11eb-80a2-6cb103c274c5.png">

This is what I would expect:

<img width="1479" alt="expectation" src="https://user-images.githubusercontent.com/2056101/102638854-1296e480-4150-11eb-908b-d458dcc5cb32.png">

Not sure if I've done something wrong in the code or there is an issue with the SDK.

Thank you!

**Comment by KKelvinLo** [comment]
Hello @noliva , thanks for reaching out! Have you tried using this [configuration](https://aws-otel.github.io/docs/getting-started/js-sdk/trace-manual-instr#tracing-aws-sdk-calls) ? This is a plugin you have to install and configure in your trace.js file you gave as an example.

**Comment by noliva** [comment]
Thank you very much @KKelvinLo for your quick response. I've added that plugin to my repository, but I can't tell the difference as I'm still seeing exactly the same as before.

**Comment by KKelvinLo** [comment]
Ah I see the issue, currently the plugin currently supports V2 AWS JS SDK and you're using the newly released V3.0.0 for dynamo DB. That plugin support is currently not in place, but it will be in the future. I apologize for any inconvenience.
