### ISSUE TITLE
AWSXRayIdGenerator vs AwsXRayIdGenerator

### ISSUE THREAD

**Issue by GiselleSerate** [aws-observability/aws-otel-js#55]
Hi there, 

I was trying to follow the instructions listed in [this readme](https://github.com/aws-observability/aws-otel-js/tree/main/packages/opentelemetry-id-generator-aws-xray#usage) and struggled for a while before I figured out that the instructions in the usage section were citing:
```js
const { AWSXRayIdGenerator } = require('@aws/otel-aws-xray-id-generator');
```
When I did this in my own code, `AWSXRayIdGenerator` was actually `undefined` (therefore unusable), and I was only able to make it work if I switched the casing:
```js
const { AwsXRayIdGenerator } = require('@aws/otel-aws-xray-id-generator');
```
[Here's a repl.it to demonstrate.](https://replit.com/@GiselleSerate/YummyChillyGreyware#index.js)
The version of `@aws/otel-aws-xray-id-generator` I'm using is `0.13.1`, although I tried switching to a couple older versions of this package with the same result. 

Not sure if this is a recent change that needs to be updated in the documentation? 

Thanks.

**Comment by anuraaga** [comment]
@GiselleSerate Sorry for the error in our docs, it definitely needs to be fixed. We're currently in the progress of moving these components to https://github.com/open-telemetry/opentelemetry-js-contrib and will make the fixes as part of that. Thanks for bringing this up.

**Comment by vasireddy99** [comment]
closing this issue, the components are moved `upstream`
