### ISSUE TITLE
"@opentelemetry/api" should be a peer dependency for Xray Propagator

### ISSUE THREAD

**Issue by kbkk** [aws-observability/aws-otel-js#56]
Hi,

Right now, the Xray Propagator (`@aws/otel-aws-xray-propagator`) does not work with `@opentelemetry/api` (API) other than 0.13.0. The reason for that is, it installs its own version of the API and therefore ignores any configuration set by the developer.

If you look at official Otel packages, those treat the API as a peerDependency, e.g.: 
https://github.com/open-telemetry/opentelemetry-js/blob/b9c842613c4439435f1644c8c8e288d1fd0e384c/packages/opentelemetry-propagator-jaeger/package.json#L75

**Comment by anuraaga** [comment]
Hi @kbkk - we've just completed migrating this package upstream so a newer version is available there!

https://www.npmjs.com/package/@opentelemetry/propagator-aws-xray

The packages in this repo are deprecated and we'll be removing them soom, please check out that package. Thanks.

**Comment by kbkk** [comment]
Awesome, looks like that is working! Thanks

If I may suggest, please mark `@aws/otel-aws-xray-propagator` as deprecated on npm - it'll save a lot of trouble for Otel newcomers.

Feel free to close the issue.

**Comment by anuraaga** [comment]
@alolita Can you mark these two packages deprecated on NPM?

**Comment by PaurushGarg** [comment]
Closing Issue as the package has been marked deprecated.
