### ISSUE TITLE
JavaScript sample app and documentation updated for metrics GA

### ISSUE THREAD

**Issue by mhausenblas** [aws-observability/aws-otel-js#87]
When [JavaScript SDK](https://github.com/open-telemetry/opentelemetry-js) goes GA for metrics make sure that:

- [x] The sample-app is up-to date
- [x] The relevant parts of the ADOT docs are updated.
- [x] Tests are up to date.

Note: this SDK is a dependency of our ADOT [Lambda](https://aws-otel.github.io/docs/getting-started/lambda) offering.

**Comment by humivo** [comment]
The [Javascript sample app](https://github.com/aws-observability/aws-otel-community/tree/master/sample-apps/javascript-sample-app) has been updated and the [ADOT docs](https://github.com/aws-otel/aws-otel.github.io/pull/529) have been updated to include metrics support as well as link the new sample app.

**Comment by humivo** [comment]
The integration testing for the Javascript sample app is also up to date and so this ticket can be closed now.
